name: deploy to azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: azure docker login
      uses: azure/docker-login@v2
      with:
        login-server: uvarenkocr.azurecr.io
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: uvarenkocr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/anton-uvarenko/auto-medicine:${{ github.sha }}
        file: ./Dockerfile

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'auto-medicine'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        images: 'uvarenkocr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/anton-uvarenko/auto-medicine:${{ github.sha }}'

